# 
FROM python:3.9

# 
WORKDIR /

# 
COPY ./requirements.txt /requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

# 
COPY ./app /app
COPY ./processed_data /processed_data

#run load_data.py
#RUN python app/load_data.py

ENV FLASK_APP=app


# Expose port 5000
EXPOSE 5000

# Set the default command to run when the container starts
CMD ["flask", "--app", "app/app", "run", "--host", "0.0.0.0"]