version: "3"
services:
  janusgraph:
    image: janusgraph/janusgraph:0.6.3 #change to a fixed version
    ports:
      - "8182:8182"
    volumes:
      -  "./configs/janusgraph:/etc/opt/janusgraph:ro"
    container_name: "janusgraph-default"

  fastapi-app:
    build: ./app/backend
    image: fast-api-uvicorn-backend
    container_name: "bdnr-backend"
    user: root
    ports:
      - "5001:80"