version: "3"
services:
  janusgraph:
    image: janusgraph/janusgraph:0.6.3 #change to a fixed version
    ports:
      - "8182:8182"
    volumes:
      -  "./configs/janusgraph:/etc/opt/janusgraph:ro"
    container_name: "janusgraph-default"
    
    
  cassandra:
    image: cassandra:3
    container_name: jc-cassandra
    ports:
      -  "9042:9042"
      -  "9160:9160"
    

  fastapi-app:
    build: ./app/backend
    image: fast-api-uvicorn-backend
    container_name: "bdnr-backend"
    user: root
    ports:
      - "5001:80"

  react-app:
    build: ./app/NetworkOfThrones
    container_name: "bdnr-frontend"
    ports:
      - "6001:5173"
    
